name: Call Copy Files for Windows
on:
  push:
    #branches: [main, feature/dk*]
    branches: main
  workflow_dispatch:

jobs:
  copy-files-job:
    uses: ./.github/workflows/reusable-copy-files.yaml
    with:
      SourceFolder: sourcefolder
      TargetFolder: targetFolder
      contents: '*.txt'
      CleanTargetFolder: true
      OverWrite: true
      FlattenFolders: true
