name: Main NuGet Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-nuget:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      solution: MyRealApp.sln
      nugetConfigPath: ./NuGet.config
      packagesDirectory: ./packages
      verbosity: detailed
      nuGetRestoreArgs: ""
      restoreMode: restore
      noCache: true
      nuGetVersion: 6.13.2.1
      nuGetPath: ./nuget.exe

      # Packager Inputs
      searchPattern: MyProject.csproj
      outputdir: ./nupkgs
      includeReferencedProjects: true
      versionByBuild: false
      versionEnvVar: ""
      requestedMajorVersion: 1
      requestedMinorVersion: 0
      requestedPatchVersion: 0
      configurationToPack: Release
      buildProperties: Platform=AnyCPU
      nuGetAdditionalArgs: ""

      # Publisher Inputs
      nuGetFeedType: internal
      connectedServiceName: AzureArtifactsConnection
      feedName: https://pkgs.dev.azure.com/YourOrg/_packaging/YourFeed/nuget/v3/index.json
      continueOnEmptyNupkgMatch: false
