name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nuget-build:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      solution: 'path/to/solution.sln'
      nugetConfigPath: 'path/to/nuget.config'
      restoreMode: 'restore'
      noCache: true
      nuGetRestoreArgs: '--force'
      verbosity: 'detailed'
      searchPattern: '**/*.csproj'
      outputdir: 'path/to/output'
      versionByBuild: true
      versionEnvVar: 'BUILD_VERSION'
      configurationToPack: 'Release'
      buildProperties: 'Configuration=Release'
      nuGetAdditionalArgs: '--include-symbols'
      nuGetFeedType: 'internal'
      feedName: 'MyNuGetFeed'
