name: NuGet Main Workflow

on:
  push:
    branches: [ main ]

jobs:
  run-nuget:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      solution: 'MyRealApp.sln'
      nugetConfigPath: './NuGet.config'
      restoreMode: 'restore'
      noCache: false
      nuGetRestoreArgs: ''
      verbosity: 'detailed'
      nuGetVersion: '6.13.2.1'
      nuGetPath: 'C:/tools/nuget'

      selectorConfig: 'Release'
      feed: 'https://api.nuget.org/v3/index.json'
      includeNuGetOrg: true
      packagesDirectory: './packages'

      searchPattern: './MyApp/MyApp.csproj'
      outputdir: './nuget_packages'
      includeReferencedProjects: true
      versionByBuild: true
      versionEnvVar: 'BUILD_VERSION'
      requestedMajorVersion: '1'
      requestedMinorVersion: '0'
      requestedPatchVersion: '3'
      configurationToPack: 'Release'
      buildProperties: 'Platform=AnyCPU'
      nuGetAdditionalArgs: ''

      nuGetFeedType: 'external'
      connectedServiceName: 'MyNuGetService'
      feedName: 'https://api.nuget.org/v3/index.json'
      continueOnEmptyNupkgMatch: false
