name: Main NuGet Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-nuget:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      solution: OrchardCore.sln
      searchPattern: src/docs/OrchardCore.Docs.csproj
      configurationToPack: Release
      outputdir: ./nupkgs
      majorVersion: 1
      minorVersion: 0
      patchVersion: 0
      apiKey: YOUR_API_KEY_HERE
      feedName: https://pkgs.dev.azure.com/YourOrg/_packaging/YourFeed/nuget/v3/index.json
