name: Main Workflow with Two Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-NPM-install-reusable:
    uses: ./.github/workflows/npm-reusable-workflow.yml
    with:
      runsOn: self-hosted
      command: "install"
      workingDir: "./npm-scripts"
      verbose: true
      customCommand: "run build:fonts"
      customRegistry: "https://registry.npmjs.org/"

  call-npm-build-reusable:
    needs: call-NPM-install-reusable
    uses: ./.github/workflows/npm-reusable-workflow.yml
    with:
      runsOn: self-hosted
      command: "custom"
      workingDir: "./npm-scripts"
      verbose: true
      customCommand: "run build:fonts"
      customRegistry: "https://registry.npmjs.org/"
