name: Main Workflow with Two Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/npm-reusable-workflow.yml
    with:
      runsOn: self-hosted
      command: "install"
      workingDir: "./npm-scripts"
      verbose: true
      customCommand: "run build:fonts"
      customRegistry: "https://registry.npmjs.org/"

  V2-Copy-Files:
    needs: call-reusable
    uses: ./.github/workflows/copy-reusable-workflow.yml
    with:
      SourceFolder: sourcefolder
      contents: '*.txt'
      #TargetFolder: targetFolder
      TargetFolder: d:\a\NUGET\NUGET\targetFolder\subfolder
      CleanTargetFolder: true
      overwrite: false
      FlattenFolders: false
      preserveTimestamp: false
      retryCount: '3'
      delayBetweenRetries: '5000'
      ignoreMakeDirErrors: false
